export type Mode = {
    id: string;
    name: string;
    summary: string;
    rules: string[];
    options: {
        value: string;
        label: string;
    }[];
    paired?: boolean;
    minimum?: number;
};
const options = (...labels: string[]) => labels.map((label, i) => ({ value: String(i), label }));
export const MODES: Mode[] = [
    { id: 'trust', name: 'Trust / Fall', summary: 'Make promises, then cooperate or betray.', paired: true, options: [{ value: 'cooperate', label: 'Cooperate' }, { value: 'betray', label: 'Betray' }], rules: ['Rotating partners secretly choose cooperate or betray.', 'Both cooperate: +30 each. Betray a cooperator: +50 / 0. Both betray: +5 each.', 'An unpaired observer gets 0. If a partner times out, a submitted choice earns +10.'] },
    { id: 'minority', name: 'Minority Vote', summary: 'Win by belonging to the smaller voting bloc.', minimum: 3, options: options('Yes', 'No'), rules: ['Negotiate alliances, then secretly vote yes or no.', 'The smaller nonempty group earns +40; the majority earns 0. A tie or unanimous vote earns +5 each.', 'No elimination: everyone returns for the next vote.'] },
    { id: 'apples', name: 'Three Apples', summary: 'Trust everyone—or profit from breaking the pact.', options: options('Red · trust', 'Gold · ambition', 'Silver · ambition'), rules: ['If everyone votes red, everyone earns +30.', 'If red mixes with gold or silver, red earns 0 and each non-red vote earns +40.', 'Without red, the majority color earns +20; minority earns 0. A tie earns +5. Unanimous gold or silver earns 0.'] },
    { id: 'contraband', name: 'Contraband', summary: 'Hide points in a case. Can the inspector call your bluff?', paired: true, options: options('Empty / inspect 0', '20 points', '40 points', '60 points'), rules: ['In each pair the first seat smuggles; the second inspects. Roles reverse each round.', 'Smuggler chooses 0, 20, 40 or 60. Inspector secretly estimates the amount.', 'Estimate at least the nonzero cargo: inspector takes it. Underestimate: smuggler keeps it. Empty case: smuggler earns half the estimate.'] },
    { id: 'downsizing', name: 'Alliance Ballot', summary: 'Spend five votes to build a coalition.', minimum: 3, options: [], rules: ['Give all five votes to another player. You cannot vote for yourself.', 'Each vote received is worth +5 points.', 'Voting earns +5 participation points; promises to exchange votes are not binding.'] },
    { id: 'roulette', name: '24 Chamber', summary: 'Choose how far to push your luck.', options: options('Stop · +5', '1 chamber · +15', '2 chambers · +30', '3 chambers · +50'), rules: ['A shared virtual wheel has 24 chambers; six are traps. No weapons or real stakes.', 'Choose 0–3 consecutive chambers. Passing all earns the listed reward; hitting any trap loses 10 points.', 'Positions are drawn by the server before choices and revealed afterward.'] },
    { id: 'poker17', name: 'Seventeen', summary: 'Draw toward 17 without going over.', options: options('Stand', 'Draw one card', 'Draw two cards'), rules: ['Your visible starting total is 8–14; the target is 17.', 'Draw cards worth 1–6, or stand. Over 17 loses 10 points.', 'Best non-busted total earns +40; other safe totals earn +10. Tied best totals share the reward.'] },
    { id: 'stationary', name: 'Stationary Wheel', summary: 'Predict where a hidden wheel stops.', options: options('Crimson', 'Gold', 'Ivory'), rules: ['Each round secretly spins a three-color wheel.', 'Choose a color. A correct prediction earns +30; a miss earns 0.', 'The wheel is committed before submissions and revealed with the results.'] },
    { id: 'pandemic', name: 'Contact Protocol', summary: 'Choose contacts carefully to collect vaccines.', options: [], minimum: 3, rules: ['Two players begin infected (one with three seats). Infection is visible; choices are secret.', 'Choose another player to contact. Both healthy: you gain one vaccine (+20).', 'Healthy contacting infected becomes infected. Infected contacting healthy recovers. States update simultaneously; infected-to-infected changes nothing.'] },
    { id: 'chairs', name: 'Steal a Chair', summary: 'Claim a seat while alliances fight over scarcity.', minimum: 3, options: options('Chair 1', 'Chair 2', 'Chair 3', 'Chair 4', 'Chair 5'), rules: ['There is one fewer chair than players. Choose an available chair secretly.', 'You cannot choose the chair you used last round. A sole claimant earns +30.', 'If several claim a chair, one is randomly selected to earn +10; others earn 0. No elimination.'] },
    { id: 'auction', name: 'Auction Poker', summary: 'Bid points to assemble the strongest five-card hand.', options: options('Bid 0', 'Bid 10', 'Bid 20', 'Bid 30'), rules: ['Everyone starts with a public five-card hand and 100 auction credits.', 'A public card is offered each round. Highest bid wins, pays credits, and replaces their weakest card. Ties are broken by a precommitted server draw.', 'The winning bid earns 0 round points; after five auctions, poker hand rank decides the match. Unspent credits break equal hands.'] },
    { id: 'kingdoms', name: 'Four Kingdoms', summary: 'Coordinate attacks and defenses between factions.', options: [], rules: ['Seats join up to four kingdoms, each starting with 100 life. Faction assignments are public.', 'Attack another kingdom for 20 damage, defend yours to block 20, or rest. Each attack/defense costs your kingdom 1 life.', 'All moves resolve together. A fallen kingdom cannot act; after five rounds, surviving life decides the winner.'] },
    { id: 'ghostleg', name: 'Ghostleg Lottery', summary: 'Secretly change the ladder that routes each prize.', options: options('Bridge lanes 1–2', 'Bridge lanes 2–3', 'Bridge lanes 3–4', 'Leave ladder alone'), rules: ['Each seat starts on one of four lanes; bottom prizes are 10, 20, 30 and 40.', 'In seating order, each submitted bridge swaps those two routes.', 'Your final lane determines your reward. This is a short standalone adaptation of the tournament lottery.'] },
    { id: 'human-auction', name: 'Team Auction', summary: 'Bid for a rotating ally and share their rewards.', options: options('Bid 0', 'Bid 10', 'Bid 20', 'Bid 30'), minimum: 3, rules: ['One rotating captain is up for auction; the captain selects a bid amount as their base reward.', 'Other seats bid 0–30. Highest bidder pays their bid in score, then gets twice the captain’s base reward. Captain gets the bid plus their base reward.', 'Others earn +5. Ties are precommitted random draws. Alliances last one round.'] },
    { id: 'goldrush', name: 'Gold Rush', summary: 'Is the hidden sack gold or a decoy?', paired: true, options: options('Decoy / Pass', 'Gold / Inspect'), rules: ['First seat smuggles a gold bar or decoy; second seat passes or inspects. Roles alternate.', 'Passing gold gives smuggler +40. Inspecting gold gives inspector +40.', 'Inspecting a decoy gives smuggler +20 and inspector −10. Passing a decoy gives both +5.'] },
    { id: 'taboo', name: 'Taboo Pact', summary: 'Set traps for your partner’s secret move.', paired: true, options: options('Circle', 'Triangle', 'Square'), rules: ['Your public forbidden symbol rotates each round.', 'Choose a symbol: if it matches your partner’s forbidden symbol, you lose 10 and your partner earns +20.', 'Otherwise you earn +15. Both players’ gains and traps resolve together.'] },
    { id: 'election', name: 'President’s Game', summary: 'Campaign for office, then decide whether to keep your promise.', minimum: 3, options: [], rules: ['Rounds 1, 3 and 5 are elections: vote for any candidate, including yourself. Most votes wins; ties use a precommitted draw.', 'The elected president gains +10. On rounds 2 and 4, the president chooses Share or Tax; everyone else votes Support or Oppose.', 'Share: everyone +20. Tax: president +50, supporters +5, opponents +10. Each president may Tax only once per match.'] },
    { id: 'survival', name: 'Last Seat Standing', summary: 'Load energy, strike, or deflect an attack.', options: options('Charge', 'Strike', 'Deflect'), rules: ['Each player starts with 3 shields, zero energy, and three deflections.', 'Charge adds one energy. Strike spends one energy and hits the next living seat for one shield. Deflect spends a deflection to redirect an incoming strike back.', 'Defeated seats observe. Surviving shields are worth 20 each, plus 5 per energy at the end.'] },
    { id: 'mask', name: 'Mask Exchange', summary: 'Read the crowd and decide who is hiding behind a mask.', options: options('Truth mask', 'Lie mask', 'Expose liars'), rules: ['This original adaptation fills in the pasted story’s unspecified Mask Game rules.', 'Truth earns +20 unless liars outnumber truth tellers. Lie earns +30 when any truth teller exists.', 'Expose earns +15 per liar, but loses 10 if nobody lies. Choices are simultaneous.'] },
    { id: 'selection', name: 'Lost Fortune', summary: 'Return the bag—or keep it and risk an audit.', options: options('Return', 'Keep', 'Audit'), rules: ['An original short adaptation of the selection scenario; all stakes are fictional points.', 'Return earns +20. Keep earns +40 unless anyone audits, in which case keep loses 20.', 'Auditors earn +20 per keeper; auditing an honest table loses 10.'] },
];
MODES.push({ id: 'vault', name: 'Vault Exchange', summary: 'Offer, guard, or attempt to take your partner’s points.', paired: true, options: options('Guard', 'Offer 20', 'Take'), rules: ['A short original adaptation of the thirty-day opening money challenge.', 'Offer transfers 20 to a partner; Guard blocks Take. Take steals 30 from an unguarded partner.', 'Both guard earns +5 each. Both take earns 0. Transfers can produce negative scores; there is no real currency.'] });
MODES.push({ ...MODES.find(m => m.id === 'pandemic')!, id: 'angels', name: 'Angels & Demons', summary: 'Contact other seats to gather light and shed your shadow.' });
export function modeOf(id?: string): Mode { return MODES.find(m => m.id === id) ?? MODES[0]; }
