import { Handshake,Swords,Check,Eye } from 'lucide-react';
import { useState } from 'react';
import type { PublicRoom } from '../../lib/game/client';
import type { Choice } from '../../lib/game/engine';
export function Table({room,seconds,busy,act}:{room:PublicRoom;seconds:number;busy:boolean;act:(action:string,payload?:Record<string,unknown>)=>Promise<boolean>}){
 const [choice,setChoice]=useState<Choice|null>(null);
 const me=room.players.find(p=>p.id===room.you)!;
 const pair=room.pairs.find(p=>p.includes(room.you)),partner=room.players.find(p=>p.id===pair?.find(id=>id!==room.you));
 const result=room.results.find(r=>r.id===room.you);
 const top=Math.max(...room.players.map(p=>p.score)),winners=room.players.filter(p=>p.score===top);
 const title=room.phase==='lobby'?'Take your seat.':room.phase==='negotiation'?'Trust has a price.':room.phase==='reveal'?'The truth is on the table.':winners.some(p=>p.id===room.you)?'You leave a winner.':'Every promise has a cost.';
 return <section className="table-content"><div className="round-heading"><h1>{title}</h1><span className="phase">{room.phase==='lobby'?'THE TABLE IS OPEN':room.phase==='negotiation'?'NEGOTIATION':room.phase==='reveal'?'THE REVEAL':'FINAL SCORES'}</span>{(room.phase==='negotiation'||room.phase==='reveal')&&<div className="timer">00:{String(seconds).padStart(2,'0')}</div>}<p className="round-context">{room.phase==='lobby'?`${room.players.length} / 6 seats filled · Invite a friend with the room code`:room.phase==='negotiation'?partner?<>Your partner: <strong>{partner.name}</strong> · Promises are not binding.</>:'You observe this round. You receive 15 points.':room.phase==='reveal'?`Next ${room.round===5?'final scores':'round'} in ${seconds}s`: `${winners.map(p=>p.name).join(' & ')} ${winners.length===1?'wins':'share the win'} with ${top} points.`}</p></div>
 <div className={`players players-${room.players.length}`}>{room.players.map((p,i)=><div className={`player ${p.id===room.you?'self':''} ${p.id===partner?.id?'partner':''}`} key={p.id}><div className={`portrait portrait-${i%4}`}><span>{room.phase==='lobby'?(p.ready?<Check size={18}/>:null):p.locked&&room.phase==='negotiation'?<Check size={18}/>:null}</span></div><div className="player-details"><span className="player-name">{p.id===room.you?'YOU':p.name}</span><strong>{p.score}</strong><small>{room.phase==='lobby'?(p.ready?'READY':'NOT READY'):room.phase==='negotiation'?(p.id===partner?.id?'YOUR PARTNER':p.locked?'LOCKED IN':'THINKING'):room.results.find(r=>r.id===p.id)?.partner===null?'OBSERVER':room.results.find(r=>r.id===p.id)?.choice?.toUpperCase()}</small></div></div>)}</div>
 {room.phase==='lobby'?<div className="decision lobby-actions"><span className="eyebrow">WAITING FOR EVERYONE</span><p>Ready up when you’ve read the rules.</p><div className="button-row"><button className={me.ready?'secondary':'primary'} disabled={busy} onClick={()=>act('ready')}>{me.ready?'Cancel ready':'I’m ready'}</button>{room.host===room.you&&<button className="primary" disabled={busy||room.players.length<2||!room.players.every(p=>p.ready)} onClick={()=>act('start')}>Start game</button>}</div>{room.host!==room.you&&<small>The host starts once everyone is ready.</small>}</div>:room.phase==='negotiation'?<div className="decision"><span className="eyebrow">YOUR SECRET CHOICE</span>{partner?<><div className="choice-row"><button className={`choice cooperate ${(room.myChoice??choice)==='cooperate'?'selected':''}`} aria-pressed={(room.myChoice??choice)==='cooperate'} disabled={busy||!!room.myChoice} onClick={()=>setChoice('cooperate')}><Handshake/><strong>COOPERATE</strong><span>Build trust. Share the reward.</span></button><button className={`choice betray ${(room.myChoice??choice)==='betray'?'selected':''}`} aria-pressed={(room.myChoice??choice)==='betray'} disabled={busy||!!room.myChoice} onClick={()=>setChoice('betray')}><Swords/><strong>BETRAY</strong><span>Take more. Risk the alliance.</span></button></div><button className="primary lock" disabled={busy||!choice||!!room.myChoice} onClick={()=>act('choice',{choice})}>{room.myChoice?<><Check size={18}/> Choice locked · waiting for the table</>:'Lock in choice'}</button><small>Only you can see your choice until the reveal.</small></>:<div className="observer"><Eye/><p>Watch the table. Your next partnership is coming.</p></div>}</div>:room.phase==='reveal'?<div className="decision reveal"><span className="eyebrow">YOUR ROUND RESULT</span><h2>+{result?.gain} <em>points</em></h2><p>{result?.partner?<>You chose <strong>{result.choice}</strong>. {partner?.name} chose <strong>{result.otherChoice}</strong>.</>:'Observer bonus. You’re back at the table next round.'}</p></div>:<div className="decision final"><span className="eyebrow">FIVE ROUNDS. NO MORE SECRETS.</span><div className="rankings">{[...room.players].sort((a,b)=>b.score-a.score).map((p,i)=><div key={p.id}><span>{i+1}. {p.name}{p.id===room.you?' (you)':''}</span><strong>{p.score}</strong></div>)}</div>{room.host===room.you?<button className="primary" disabled={busy} onClick={()=>act('rematch')}>Open a rematch</button>:<p>Waiting for the host to open a rematch.</p>}</div>}
 <div className="payoffs"><span>ROUND OUTCOMES</span><p>Both cooperate: <strong>+30 each</strong></p><p>One betrays: <strong>+50 / 0</strong></p><p>Both betray: <strong>+5 each</strong></p></div></section>
}
